"""
Simplified output formatting - removed complex PDF generation.
Frontend uses browser's print-to-PDF feature instead.
"""
import markdown2
from datetime import datetime
import logging

logger = logging.getLogger(__name__)


class ReportGenerator:
    """Generate styled HTML from markdown."""
    
    @staticmethod
    def markdown_to_html(markdown_content: str) -> str:
        """
        Convert markdown to print-ready HTML.
        Frontend can use window.print() for PDF generation.
        """
        extras = ["tables", "fenced-code-blocks", "header-ids", "footnotes"]
        html = markdown2.markdown(markdown_content, extras=extras)
        
        styled_html = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="UTF-8">
            <title>MARA Research Report</title>
            <style>
                @media print {{
                    body {{ margin: 0; }}
                    .no-print {{ display: none; }}
                }}
                body {{
                    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Arial, sans-serif;
                    line-height: 1.6;
                    max-width: 900px;
                    margin: 0 auto;
                    padding: 40px 20px;
                    color: #1e293b;
                }}
                h1 {{
                    color: #0f172a;
                    border-bottom: 3px solid #3b82f6;
                    padding-bottom: 10px;
                    margin-bottom: 30px;
                }}
                h2 {{
                    color: #1e40af;
                    margin-top: 40px;
                    margin-bottom: 20px;
                }}
                h3 {{
                    color: #475569;
                    margin-top: 30px;
                }}
                a {{
                    color: #2563eb;
                    text-decoration: none;
                }}
                a:hover {{
                    text-decoration: underline;
                }}
                code {{
                    background: #f1f5f9;
                    padding: 2px 6px;
                    border-radius: 3px;
                    font-family: 'Courier New', monospace;
                    font-size: 0.9em;
                }}
                pre {{
                    background: #f8fafc;
                    border: 1px solid #e2e8f0;
                    border-radius: 6px;
                    padding: 16px;
                    overflow-x: auto;
                }}
                blockquote {{
                    border-left: 4px solid #cbd5e1;
                    margin: 20px 0;
                    padding-left: 20px;
                    color: #64748b;
                }}
                table {{
                    width: 100%;
                    border-collapse: collapse;
                    margin: 20px 0;
                }}
                th, td {{
                    border: 1px solid #e2e8f0;
                    padding: 12px;
                    text-align: left;
                }}
                th {{
                    background: #f1f5f9;
                    font-weight: 600;
                }}
                .footer {{
                    margin-top: 60px;
                    padding-top: 20px;
                    border-top: 1px solid #e2e8f0;
                    color: #94a3b8;
                    font-size: 14px;
                }}
            </style>
        </head>
        <body>
            <button class="no-print" onclick="window.print()" 
                    style="position:fixed;top:20px;right:20px;padding:10px 20px;
                           background:#3b82f6;color:white;border:none;border-radius:6px;
                           cursor:pointer;font-size:14px;box-shadow:0 2px 8px rgba(0,0,0,0.1);">
                Print / Save as PDF
            </button>
            
            {html}
            
            <div class="footer">
                <p>Generated by MARA Research Assistant</p>
                <p>Date: {datetime.now().strftime("%B %d, %Y at %H:%M")}</p>
            </div>
        </body>
        </html>
        """
        return styled_html